spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_bank
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update